"""add dashboard_configs

Revision ID: 5a958714454d
Revises: 0002
Create Date: 2026-06-26 13:58:38.614104

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5a958714454d'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dashboard_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dashboard_configs_username'), ['username'], unique=True)

    with op.batch_alter_table('cache_view_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cache_view_configs_collection'))
        batch_op.create_index(batch_op.f('ix_cache_view_configs_target_collection'), ['target_collection'], unique=True)

    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_keys_key'))
        batch_op.create_index(batch_op.f('ix_idempotency_keys_key'), ['key'], unique=True)

    with op.batch_alter_table('job_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedules_next_run_time'))
        batch_op.drop_index(batch_op.f('ix_schedules_task_ref'))
        batch_op.create_index(batch_op.f('ix_job_schedules_next_run_time'), ['next_run_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_schedules_task_ref'), ['task_ref'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_schedules_task_ref'))
        batch_op.drop_index(batch_op.f('ix_job_schedules_next_run_time'))
        batch_op.create_index(batch_op.f('ix_schedules_task_ref'), ['task_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedules_next_run_time'), ['next_run_time'], unique=False)

    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_keys_key'))
        batch_op.create_index(batch_op.f('ix_idempotency_keys_key'), ['key'], unique=False)

    with op.batch_alter_table('cache_view_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cache_view_configs_target_collection'))
        batch_op.create_index(batch_op.f('ix_cache_view_configs_collection'), ['target_collection'], unique=1)

    with op.batch_alter_table('dashboard_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboard_configs_username'))

    op.drop_table('dashboard_configs')
    # ### end Alembic commands ###
